# To be imported from ezpublish.yml in the following way:
#
# imports:
#     - { resource: "@AcmeEzBlogBundle/Resources/config/blog_settings.yml" }
ezpublish:
    siteaccess:
        # Adding ezblog as valid siteaccess
        list:
            - ezblog
        groups:
            # We want ezblog in the main siteaccess group (i.e. sharing DB connection)
            ezdemo_site_group:
                - ezblog

    system:
        ezblog:
            content:
                # Use multisite feature and make ezblog start at location #90
                tree_root:
                    location_id: 90

            # Template rules for location view
            # See https://confluence.ez.no/display/EZP/View+provider+configuration
            location_view:
                full:
                    blog:
                        controller: "AcmeEzBlogBundle:Default:listBlogPosts"
                        match:
                            Identifier\ContentType: [blog]
                    blog_post:
                        controller: "AcmeEzBlogBundle:Default:showBlogPost"
                        template: "AcmeEzBlogBundle:full:blog_post.html.twig"
                        match:
                            Identifier\ContentType: [blog_post]
                line:
                    blog_post:
                        controller: "AcmeEzBlogBundle:Default:showBlogPost"
                        template: "AcmeEzBlogBundle:line:blog_post.html.twig"
                        match:
                            Identifier\ContentType: [blog_post]
