parameters:
    ezpublish_legacy.ezblog.view_default_layout: 'AcmeEzBlogBundle::pagelayout.html.twig'
    ezpublish_legacy.ezblog.module_default_layout: 'AcmeEzBlogBundle::pagelayout_legacy.html.twig'

services:
#    acme_ez_blog.example:
#        class: %acme_ez_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
