parameters:
#    acme_ez_blog.example.class: Acme\EzBlogBundle\Example

services:
#    acme_ez_blog.example:
#        class: %acme_ez_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
